/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Client, Configuration, Environment } from '../src';

export const testClient = new Client(createConfigurationFromEnvironment());

function createConfigurationFromEnvironment(): Partial<Configuration> {
  const config: Partial<Configuration> = {};

  const environment = process.env.MIST_API_LIB_ENVIRONMENT;
  const timeout = process.env.MIST_API_LIB_TIMEOUT;
  const authorization = process.env.MIST_API_LIB_AUTHORIZATION;
  const username = process.env.MIST_API_LIB_USERNAME;
  const password = process.env.MIST_API_LIB_PASSWORD;
  const xCSRFToken = process.env.MIST_API_LIB_X_CSRF_TOKEN;

  if (environment !== undefined) {
    config.environment = environment as Environment;
  }

  if (timeout !== undefined && timeout !== '') {
    config.timeout = parseInt(timeout);
  }

  if (authorization !== undefined) {
    config.apiTokenCredentials = { Authorization: authorization };
  }

  if (username !== undefined && password !== undefined) {
    config.basicAuthCredentials = { username: username, password: password };
  }

  if (xCSRFToken !== undefined) {
    config.csrfTokenCredentials = { 'X-CSRFToken': xCSRFToken };
  }

  return config;
}
