/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ApiV1OrgsNacportalsPortalTemplate403
 */
interface ApiV1OrgsNacportalsPortalTemplate403 {
  detail?: string;
}

export class ApiV1OrgsNacportalsPortalTemplate403Error extends ApiError<
  ApiV1OrgsNacportalsPortalTemplate403
> {}
