/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ApiV1OrgsNacportalsFailures403
 */
interface ApiV1OrgsNacportalsFailures403 {
  detail?: string;
}

export class ApiV1OrgsNacportalsFailures403Error extends ApiError<
  ApiV1OrgsNacportalsFailures403
> {}
