/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ApiV1OrgsNacportalsPortalImage400
 */
interface ApiV1OrgsNacportalsPortalImage400 {
  detail?: string;
}

export class ApiV1OrgsNacportalsPortalImage400Error extends ApiError<
  ApiV1OrgsNacportalsPortalImage400
> {}
