/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ApiV1OrgsNacportalsPortalTemplate401
 */
interface ApiV1OrgsNacportalsPortalTemplate401 {
  detail?: string;
}

export class ApiV1OrgsNacportalsPortalTemplate401Error extends ApiError<
  ApiV1OrgsNacportalsPortalTemplate401
> {}
