/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ApiV1OrgsNacportals403
 */
interface ApiV1OrgsNacportals403 {
  detail?: string;
}

export class ApiV1OrgsNacportals403Error extends ApiError<
  ApiV1OrgsNacportals403
> {}
