/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ApiV1OrgsNacportalsPortalTemplate429
 */
interface ApiV1OrgsNacportalsPortalTemplate429 {
  detail?: string;
}

export class ApiV1OrgsNacportalsPortalTemplate429Error extends ApiError<
  ApiV1OrgsNacportalsPortalTemplate429
> {}
