/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ApiV1OrgsNactags401
 */
interface ApiV1OrgsNactags401 {
  detail?: string;
}

export class ApiV1OrgsNactags401Error extends ApiError<ApiV1OrgsNactags401> {}
