/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ApiV1OrgsNactags400
 */
interface ApiV1OrgsNactags400 {
  detail?: string;
}

export class ApiV1OrgsNactags400Error extends ApiError<ApiV1OrgsNactags400> {}
