/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ApiV1OrgsNacportalsFailures401
 */
interface ApiV1OrgsNacportalsFailures401 {
  detail?: string;
}

export class ApiV1OrgsNacportalsFailures401Error extends ApiError<
  ApiV1OrgsNacportalsFailures401
> {}
