/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ApiV1OrgsNacportalsPortalImage403
 */
interface ApiV1OrgsNacportalsPortalImage403 {
  detail?: string;
}

export class ApiV1OrgsNacportalsPortalImage403Error extends ApiError<
  ApiV1OrgsNacportalsPortalImage403
> {}
