/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ApiV1OrgsNactags429
 */
interface ApiV1OrgsNactags429 {
  detail?: string;
}

export class ApiV1OrgsNactags429Error extends ApiError<ApiV1OrgsNactags429> {}
