/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ApiV1OrgsNacportalsPortalImage401
 */
interface ApiV1OrgsNacportalsPortalImage401 {
  detail?: string;
}

export class ApiV1OrgsNacportalsPortalImage401Error extends ApiError<
  ApiV1OrgsNacportalsPortalImage401
> {}
