/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ApiV1OrgsNacportals429
 */
interface ApiV1OrgsNacportals429 {
  detail?: string;
}

export class ApiV1OrgsNacportals429Error extends ApiError<
  ApiV1OrgsNacportals429
> {}
