/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ApiV1OrgsNacportalsFailures429
 */
interface ApiV1OrgsNacportalsFailures429 {
  detail?: string;
}

export class ApiV1OrgsNacportalsFailures429Error extends ApiError<
  ApiV1OrgsNacportalsFailures429
> {}
