/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ApiV1OrgsNacportalsPortalTemplate400
 */
interface ApiV1OrgsNacportalsPortalTemplate400 {
  detail?: string;
}

export class ApiV1OrgsNacportalsPortalTemplate400Error extends ApiError<
  ApiV1OrgsNacportalsPortalTemplate400
> {}
