/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ResponseHttp404
 */
interface ResponseHttp404 {
  id?: string;
}

export class ResponseHttp404Error extends ApiError<ResponseHttp404> {}
