/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for NacPortalTypeEnum
 */
export enum NacPortalTypeEnum {
  MarvisClient = 'marvis_client',
  Guest = 'guest',
}

/**
 * Schema for NacPortalTypeEnum
 */
export const nacPortalTypeEnumSchema: Schema<NacPortalTypeEnum> = stringEnum(
  NacPortalTypeEnum
);
