/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface NacPortalSsoRoleMatching {
  assigned?: string;
  match?: string;
}

export const nacPortalSsoRoleMatchingSchema: Schema<NacPortalSsoRoleMatching> = object(
  {
    assigned: ['assigned', optional(string())],
    match: ['match', optional(string())],
  }
);
