/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for NacPortalAccessTypeEnum
 */
export enum NacPortalAccessTypeEnum {
  Wireless = 'wireless',
  EnumWirelesswired = 'wireless+wired',
}

/**
 * Schema for NacPortalAccessTypeEnum
 */
export const nacPortalAccessTypeEnumSchema: Schema<NacPortalAccessTypeEnum> = stringEnum(
  NacPortalAccessTypeEnum
);
