/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';
import {
  NacRuleMatchingAuthTypeEnum,
  nacRuleMatchingAuthTypeEnumSchema,
} from './nacRuleMatchingAuthTypeEnum';
import {
  NacRuleMatchingPortTypeEnum,
  nacRuleMatchingPortTypeEnumSchema,
} from './nacRuleMatchingPortTypeEnum';

export interface NacRuleMatching {
  authType?: NacRuleMatchingAuthTypeEnum;
  nactags?: string[];
  portTypes?: NacRuleMatchingPortTypeEnum[];
  /** list of site ids to match */
  siteIds?: string[];
  /** list of sitegroup ids to match */
  sitegroupIds?: string[];
  /** list of vendors to match */
  vendor?: string[];
}

export const nacRuleMatchingSchema: Schema<NacRuleMatching> = object({
  authType: ['auth_type', optional(nacRuleMatchingAuthTypeEnumSchema)],
  nactags: ['nactags', optional(array(string()))],
  portTypes: ['port_types', optional(array(nacRuleMatchingPortTypeEnumSchema))],
  siteIds: ['site_ids', optional(array(string()))],
  sitegroupIds: ['sitegroup_ids', optional(array(string()))],
  vendor: ['vendor', optional(array(string()))],
});
