/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for NacRuleMatchingAuthTypeEnum
 */
export enum NacRuleMatchingAuthTypeEnum {
  Cert = 'cert',
  Deviceauth = 'device-auth',
  Eapteap = 'eap-teap',
  Eaptls = 'eap-tls',
  Eapttls = 'eap-ttls',
  Idp = 'idp',
  Mab = 'mab',
  Peaptls = 'peap-tls',
  Psk = 'psk',
}

/**
 * Schema for NacRuleMatchingAuthTypeEnum
 */
export const nacRuleMatchingAuthTypeEnumSchema: Schema<NacRuleMatchingAuthTypeEnum> = stringEnum(
  NacRuleMatchingAuthTypeEnum
);
