/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for NacRuleMatchingPortTypeEnum
 */
export enum NacRuleMatchingPortTypeEnum {
  Wired = 'wired',
  Wireless = 'wireless',
}

/**
 * Schema for NacRuleMatchingPortTypeEnum
 */
export const nacRuleMatchingPortTypeEnumSchema: Schema<NacRuleMatchingPortTypeEnum> = stringEnum(
  NacRuleMatchingPortTypeEnum
);
