/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for NacRuleActionEnum
 */
export enum NacRuleActionEnum {
  Allow = 'allow',
  Block = 'block',
}

/**
 * Schema for NacRuleActionEnum
 */
export const nacRuleActionEnumSchema: Schema<NacRuleActionEnum> = stringEnum(
  NacRuleActionEnum
);
