/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for NacTagUsernameAttrEnum
 */
export enum NacTagUsernameAttrEnum {
  Automatic = 'automatic',
  Cn = 'cn',
  Upn = 'upn',
  Email = 'email',
  Dns = 'dns',
}

/**
 * Schema for NacTagUsernameAttrEnum
 */
export const nacTagUsernameAttrEnumSchema: Schema<NacTagUsernameAttrEnum> = stringEnum(
  NacTagUsernameAttrEnum
);
