/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for NacTagMatchEnum
 */
export enum NacTagMatchEnum {
  CertCn = 'cert_cn',
  CertIssuer = 'cert_issuer',
  CertSan = 'cert_san',
  CertSerial = 'cert_serial',
  CertSub = 'cert_sub',
  ClientMac = 'client_mac',
  IdpRole = 'idp_role',
  MdmStatus = 'mdm_status',
  RadiusGroup = 'radius_group',
  Realm = 'realm',
  Ssid = 'ssid',
  UserName = 'user_name',
  UsermacLabel = 'usermac_label',
}

/**
 * Schema for NacTagMatchEnum
 */
export const nacTagMatchEnumSchema: Schema<NacTagMatchEnum> = stringEnum(
  NacTagMatchEnum
);
