/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for NacTagTypeEnum
 */
export enum NacTagTypeEnum {
  EgressVlanNames = 'egress_vlan_names',
  GbpTag = 'gbp_tag',
  Match = 'match',
  RadiusAttrs = 'radius_attrs',
  RadiusGroup = 'radius_group',
  RadiusVendorAttrs = 'radius_vendor_attrs',
  SessionTimeout = 'session_timeout',
  UsernameAttr = 'username_attr',
  Vlan = 'vlan',
}

/**
 * Schema for NacTagTypeEnum
 */
export const nacTagTypeEnumSchema: Schema<NacTagTypeEnum> = stringEnum(
  NacTagTypeEnum
);
