/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface NameString {
  name?: string;
}

export const nameStringSchema: Schema<NameString> = object({
  name: ['name', optional(string())],
});
