/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface NetworkStaticNatProperty {
  internalIp?: string;
  name?: string;
  /** If not set, we configure the nat policies against all WAN ports for simplicity */
  wanName?: string;
}

export const networkStaticNatPropertySchema: Schema<NetworkStaticNatProperty> = object(
  {
    internalIp: ['internal_ip', optional(string())],
    name: ['name', optional(string())],
    wanName: ['wan_name', optional(string())],
  }
);
