/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface NetworkDestinationNatProperty {
  internalIp?: string;
  name?: string;
  port?: number;
}

export const networkDestinationNatPropertySchema: Schema<NetworkDestinationNatProperty> = object(
  {
    internalIp: ['internal_ip', optional(string())],
    name: ['name', optional(string())],
    port: ['port', optional(number())],
  }
);
