/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import {
  ResponseSsoFailureSearchItem,
  responseSsoFailureSearchItemSchema,
} from './responseSsoFailureSearchItem';

export interface ResponseSsoFailureSearch {
  results: ResponseSsoFailureSearchItem[];
}

export const responseSsoFailureSearchSchema: Schema<ResponseSsoFailureSearch> = object(
  {
    results: ['results', array(lazy(() => responseSsoFailureSearchItemSchema))],
  }
);
