/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface ResponseSsoFailureSearchItem {
  detail: string;
  samlAssertionXml: string;
  timestamp: number;
}

export const responseSsoFailureSearchItemSchema: Schema<ResponseSsoFailureSearchItem> = object(
  {
    detail: ['detail', string()],
    samlAssertionXml: ['saml_assertion_xml', string()],
    timestamp: ['timestamp', number()],
  }
);
