/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  basicAuthenticationProvider,
  compositeAuthenticationProvider,
  customHeaderAuthenticationProvider,
} from './authentication';
import { Configuration } from './configuration';

export function createAuthProviderFromConfig(config: Partial<Configuration>) {
  const authConfig = {
    apiToken:
      config.apiTokenCredentials &&
      customHeaderAuthenticationProvider(config.apiTokenCredentials),
    basicAuth:
      config.basicAuthCredentials &&
      basicAuthenticationProvider(
        config.basicAuthCredentials.username,
        config.basicAuthCredentials.password
      ),
    csrfToken:
      config.csrfTokenCredentials &&
      customHeaderAuthenticationProvider(config.csrfTokenCredentials),
  };

  return compositeAuthenticationProvider<
    keyof typeof authConfig,
    typeof authConfig
  >(authConfig);
}
