/**
 * Mist APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { HttpClientOptions } from './clientAdapter';

/** An interface for all configuration parameters required by the SDK. */
export interface Configuration {
  timeout: number;
  environment: Environment;
  apiTokenCredentials?: {
    'Authorization': string;
  };
  basicAuthCredentials?: {
    username: string;
    password: string;
  };
  csrfTokenCredentials?: {
    'X-CSRFToken': string;
  };
  httpClientOptions?: Partial<HttpClientOptions>;
  unstable_httpClientOptions?: any;
}

/** Environments available for API */
export enum Environment {
  Production = 'production',
  Environment2 = 'environment2',
  Environment3 = 'environment3',
  Environment4 = 'environment4',
  Environment5 = 'environment5',
  Environment6 = 'environment6',
  Environment7 = 'environment7',
  Environment8 = 'environment8',
}
